name: Bojagi upload workflow

on:
  workflow_run:
    workflows: ['Bojagi build workflow']
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn --pure-lockfile --non-interactive

      - name: 'Download artifact'
        uses: actions/github-script@v3.1.1
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });

            console.log('run id', ${{github.event.workflow_run.id }});

            console.log('artifacts.data.artifacts', artifacts.data.artifacts);

            var matchArtifact = artifacts.data.artifacts.find((artifact) => {
              return artifact.name == "bojagi"
            });

            console.log('matchArtifact', matchArtifact);

            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });

            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/.bojagi.zip', Buffer.from(download.data));

      - name: Decompress .bojagi files
        run: unzip ./.bojagi.zip -d ./.bojagi/tmp

      - name: Upload
        run: yarn bojagi upload
        env:
          BOJAGI_SECRET: ${{ secrets.BOJAGI_SECRET }}
